version: '2'
services:
  database:
    image: postgres:10.5
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=db_for_eventstore
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
